FROM node:latest

RUN useradd -m app

USER app
WORKDIR /home/app

VOLUME /home/app

EXPOSE 3000

ENV ACTIVEMQ_USER subscriber
ENV ACTIVEMQ_PASSWORD subscriber

CMD npm install && DEBUG=* node src/app.js

